// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lab
void lab(SEXP lac, SEXP lbc, SEXP SL, SEXP TA, SEXP lambda, SEXP kapp, SEXP gamm, SEXP delta, SEXP nml, int no, int n);
RcppExport SEXP CCRWvsLW_lab(SEXP lacSEXP, SEXP lbcSEXP, SEXP SLSEXP, SEXP TASEXP, SEXP lambdaSEXP, SEXP kappSEXP, SEXP gammSEXP, SEXP deltaSEXP, SEXP nmlSEXP, SEXP noSEXP, SEXP nSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type lac(lacSEXP );
        Rcpp::traits::input_parameter< SEXP >::type lbc(lbcSEXP );
        Rcpp::traits::input_parameter< SEXP >::type SL(SLSEXP );
        Rcpp::traits::input_parameter< SEXP >::type TA(TASEXP );
        Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type kapp(kappSEXP );
        Rcpp::traits::input_parameter< SEXP >::type gamm(gammSEXP );
        Rcpp::traits::input_parameter< SEXP >::type delta(deltaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type nml(nmlSEXP );
        Rcpp::traits::input_parameter< int >::type no(noSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        lab(lac, lbc, SL, TA, lambda, kapp, gamm, delta, nml, no, n);
    }
    return R_NilValue;
END_RCPP
}
// EMHMM
SEXP EMHMM(SEXP SL, SEXP TA, SEXP ml, SEXP nml, SEXP SLmin, SEXP lambda, SEXP gamm, SEXP delta, SEXP kapp, SEXP maxiter, SEXP tol, SEXP op);
RcppExport SEXP CCRWvsLW_EMHMM(SEXP SLSEXP, SEXP TASEXP, SEXP mlSEXP, SEXP nmlSEXP, SEXP SLminSEXP, SEXP lambdaSEXP, SEXP gammSEXP, SEXP deltaSEXP, SEXP kappSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP opSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type SL(SLSEXP );
        Rcpp::traits::input_parameter< SEXP >::type TA(TASEXP );
        Rcpp::traits::input_parameter< SEXP >::type ml(mlSEXP );
        Rcpp::traits::input_parameter< SEXP >::type nml(nmlSEXP );
        Rcpp::traits::input_parameter< SEXP >::type SLmin(SLminSEXP );
        Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type gamm(gammSEXP );
        Rcpp::traits::input_parameter< SEXP >::type delta(deltaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type kapp(kappSEXP );
        Rcpp::traits::input_parameter< SEXP >::type maxiter(maxiterSEXP );
        Rcpp::traits::input_parameter< SEXP >::type tol(tolSEXP );
        Rcpp::traits::input_parameter< SEXP >::type op(opSEXP );
        SEXP __result = EMHMM(SL, TA, ml, nml, SLmin, lambda, gamm, delta, kapp, maxiter, tol, op);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// p2c
SEXP p2c(SEXP SL, SEXP TA);
RcppExport SEXP CCRWvsLW_p2c(SEXP SLSEXP, SEXP TASEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type SL(SLSEXP );
        Rcpp::traits::input_parameter< SEXP >::type TA(TASEXP );
        SEXP __result = p2c(SL, TA);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// sslta
SEXP sslta(SEXP n, SEXP a, SEXP lambda, SEXP kapp, SEXP ai2, SEXP delta);
RcppExport SEXP CCRWvsLW_sslta(SEXP nSEXP, SEXP aSEXP, SEXP lambdaSEXP, SEXP kappSEXP, SEXP ai2SEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type n(nSEXP );
        Rcpp::traits::input_parameter< SEXP >::type a(aSEXP );
        Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type kapp(kappSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ai2(ai2SEXP );
        Rcpp::traits::input_parameter< SEXP >::type delta(deltaSEXP );
        SEXP __result = sslta(n, a, lambda, kapp, ai2, delta);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
