# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lab <- function(lac, lbc, SL, TA, lambda, kapp, gamm, delta, nml, no, n) {
    invisible(.Call('CCRWvsLW_lab', PACKAGE = 'CCRWvsLW', lac, lbc, SL, TA, lambda, kapp, gamm, delta, nml, no, n))
}

EMHMM <- function(SL, TA, ml, nml, SLmin, lambda, gamm, delta, kapp, maxiter, tol, op) {
    .Call('CCRWvsLW_EMHMM', PACKAGE = 'CCRWvsLW', SL, TA, ml, nml, SLmin, lambda, gamm, delta, kapp, maxiter, tol, op)
}

p2c <- function(SL, TA) {
    .Call('CCRWvsLW_p2c', PACKAGE = 'CCRWvsLW', SL, TA)
}

sslta <- function(n, a, lambda, kapp, ai2, delta) {
    .Call('CCRWvsLW_sslta', PACKAGE = 'CCRWvsLW', n, a, lambda, kapp, ai2, delta)
}

